# Generated by Django 2.2.6 on 2019-12-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20191220_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('fuel_type', models.CharField(choices=[('H', 'Hybrid'), ('P', 'Petrol'), ('D', 'Diesel')], max_length=1)),
                ('gear_type', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1)),
                ('hire_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.Vehicle_Type')),
            ],
        ),
    ]
