# Generated by Django 2.2.6 on 2019-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.FileField(blank=True, upload_to='vehicles/'),
        ),
    ]
