# Generated by Django 2.2.6 on 2019-12-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20191220_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_datetime',
            field=models.DateTimeField(),
        ),
    ]
