# Generated by Django 2.2.6 on 2019-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20191220_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
