# Generated by Django 2.2.6 on 2019-12-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='from_dates',
            new_name='from_date',
        ),
    ]
