# Generated by Django 2.2.6 on 2019-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20191221_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
