# Generated by Django 2.2.6 on 2019-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20191221_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gear_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=1),
        ),
    ]
