# Generated by Django 2.2.6 on 2019-12-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_auto_20191223_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('H', 'Hybrid'), ('P', 'Petrol'), ('D', 'Diesel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gear_type',
            field=models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1),
        ),
    ]
