# Generated by Django 2.2.6 on 2019-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_auto_20191223_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(),
        ),
    ]
