# Generated by Django 2.2.6 on 2019-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_auto_20191224_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FileField(upload_to='vehicles/'),
        ),
    ]
